# Change to user's credentials
# org: users-credentials
service: nam-group24
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    DYNAMODB_TABLE: accounts # Will create a dynamodb table named accounts
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:*:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  createAccount:
    handler: lambdas/createAccount.handler
    events:
      - http:
          path: create-account/{ID}
          method: GET
          cors: true

resources:
  Resources:
    accounts:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: acct-id
            AttributeType: N
        KeySchema:
          - AttributeName: acct-id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-plugin-scripts

custom:
  scripts:
    commands:
      init-db: aws dynamodb put-item --table-name accounts --item file://default-account.json
