service: nam-group24
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser

functions:
  createAccount:
    handler: lambdas/createAccount.handler
    events:
      - http:
          path: test
          method: GET
          cors: true